# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 443)
        MainWindow.setStyleSheet("background-color: rgb(57, 114, 171);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.temperature = QtWidgets.QLabel(self.centralwidget)
        self.temperature.setGeometry(QtCore.QRect(160, 120, 81, 71))
        self.temperature.setStyleSheet("background-color: rgb(57, 114, 171);\n"
"font: 75 46pt \"Calibri\" bold;\n"
"color: rgb(255, 255, 255)")
        self.temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature.setObjectName("temperature")
        self.city = QtWidgets.QLabel(self.centralwidget)
        self.city.setGeometry(QtCore.QRect(90, 60, 221, 31))
        self.city.setStyleSheet("background-color: rgb(57, 114, 171);\n"
"font: 75 20pt \"Calibri\" bold;\n"
"color: rgb(255, 255, 255);")
        self.city.setAlignment(QtCore.Qt.AlignCenter)
        self.city.setObjectName("city")
        self.search_line = QtWidgets.QLineEdit(self.centralwidget)
        self.search_line.setGeometry(QtCore.QRect(20, 20, 171, 20))
        self.search_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #e6e8ff;")
        self.search_line.setObjectName("search_line")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(200, 20, 75, 20))
        self.search_button.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.search_button.setObjectName("search_button")
        self.wet = QtWidgets.QLabel(self.centralwidget)
        self.wet.setGeometry(QtCore.QRect(20, 240, 101, 21))
        self.wet.setStyleSheet("background-color: rgb(57, 114, 171);\n"
"font: 75 13pt \"Calibri\" bold;\n"
"color: rgb(255, 255, 255)")
        self.wet.setObjectName("wet")
        self.sunrise = QtWidgets.QLabel(self.centralwidget)
        self.sunrise.setGeometry(QtCore.QRect(20, 300, 101, 30))
        self.sunrise.setStyleSheet("background-color: rgb(57, 114, 171);\n"
"font: 75 13pt \"Calibri\" bold;\n"
"color: rgb(255, 255, 255)")
        self.sunrise.setObjectName("sunrise")
        self.sunset = QtWidgets.QLabel(self.centralwidget)
        self.sunset.setGeometry(QtCore.QRect(20, 360, 101, 31))
        self.sunset.setStyleSheet("background-color: rgb(57, 114, 171);\n"
"font: 75 13pt \"Calibri\" bold;\n"
"color: rgb(255, 255, 255)")
        self.sunset.setObjectName("sunset")       
        self.sunrise_text = QtWidgets.QLabel(self.centralwidget)# ВОСХОД
        self.sunrise_text.setGeometry(QtCore.QRect(140, 300, 70, 30))# ВОСХОД
        self.sunrise_text.setStyleSheet("background-color: rgb(57, 114, 171);\n"# ВОСХОД
"font: 75 13pt \"Calibri\" bold;\n"
"color: rgb(255, 255, 255)")
        self.sunrise_text.setObjectName("wet_text")# ВОСХОД
        self.sunset_text = QtWidgets.QLabel(self.centralwidget) #ЗАКАТ
        self.sunset_text.setGeometry(QtCore.QRect(140, 360, 71, 30))#ЗАКАТ
        self.sunset_text.setStyleSheet("background-color: rgb(57, 114, 171);\n"#ЗАКАТ
"font: 75 13pt \"Calibri\" bold;\n"
"color: rgb(255, 255, 255)")
        self.sunset_text.setObjectName("sunrise_text")#ЗАКАТ
        self.wet_text = QtWidgets.QLabel(self.centralwidget)# ВЛАЖНОСТЬ
        self.wet_text.setGeometry(QtCore.QRect(140, 237, 71, 30)) # ВЛАЖНОСТЬ
        self.wet_text.setStyleSheet("background-color: rgb(57, 114, 171);\n"# ВЛАЖНОСТЬ
"font: 75 13pt \"Calibri\" bold;\n"
"color: rgb(255, 255, 255)")
        self.wet_text.setObjectName("sunset_text")# ВЛАЖНОСТЬ
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Прогноз погоды"))
        self.temperature.setText(_translate("MainWindow", ''))
        self.city.setText(_translate("MainWindow", ''))
        self.search_line.setPlaceholderText(_translate("MainWindow", "Введите название города"))
        self.search_button.setText(_translate("MainWindow", "Найти"))
        self.search_button.clicked.connect(self.get_weather)
        self.wet.setText(_translate("MainWindow", "Влажность"))
        self.sunrise.setText(_translate("MainWindow", "Восход"))
        self.sunset.setText(_translate("MainWindow", "Закат"))
        self.wet_text.setText(_translate("MainWindow", "0"))
        self.sunrise_text.setText(_translate("MainWindow", "0"))
        self.sunset_text.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
